### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by ParkJong-Hun** [ParkJong-Hun/wihd-2025#1]
## App
Guitar community app.

### TODO
- [ ] Movie Screens with Jetpack Compose
- [ ] Guitar guide Screens with Bitmap
- [ ] Testable Code
- [ ] Use my library
- [ ] **Not use onion architecture**
- [ ] **Not use material design**
